In [1]:
import numpy as np
import tensorflow as tf
import torch
list = []
for i in range(0,12):
    list.append(i)
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [2]:
arr = np.array(list)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
tensor_1d =  torch.tensor(list)
tensor_1d

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
tensor_1d_tf = tf.convert_to_tensor(list)
tensor_1d_tf

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [5]:
tensor_1d_tf.shape

TensorShape([12])

In [6]:
list_2D = [[1, 4, 7, 10], 
           [2, 5, 8, 11],
           [3, 6, 9, 12]]

In [7]:
arr_2D= np.array(list_2D)
arr_2D

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [8]:
arr_2D.shape

(3, 4)

In [9]:
type(arr_2D)

numpy.ndarray

In [10]:
arr_2D.dtype

dtype('int32')

In [15]:
np.zeros(arr_2D.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
torch.zeros(arr_2D.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
tf.zeros(arr_2D.shape)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [18]:
np.ones(arr_2D.shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
torch.ones(arr_2D.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
tf.ones(arr_2D.shape)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [22]:
np.full(arr_2D.shape, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [23]:
torch.full(arr_2D.shape,9)

tensor([[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]])

In [26]:
tf.fill(arr_2D.shape,2)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])>

## Phep tinh ss

In [ ]:
# chuyen vi
